### ISSUE TITLE
name sanitization

### ISSUE THREAD

**Issue by akhmerov** [jupyterhub/firstuseauthenticator#5]
@yuvipanda first of all, thank you very much for this extremely useful tool!

The issue: right now if the username contains spaces, the single user server fails to start somewhere down the pipeline. This might also indicate a vulnerability. Perhaps the username should be sanitized or filtered.

**Comment by leportella** [comment]
I was thinking about doing this. Would it be better to pop something saying it is not allowing username with spaces? What are your thoughts on this @yuvipanda @minrk :)

**Comment by minrk** [comment]
@leportella yes, I think that's a good idea. There's already a mechanism to validate usernames, in a method called `.validate_username` on the base Authenticator class.

By default, this looks at the `.username_pattern`, which is a regular expression string. You can use this to prohibit spaces.

One version to hard-prohibit spaces is to add a strict validation to the subclass:

```python
def validate_username(self, name):
    if ' ' in name:
        return False
    return super().validate_username()
```

It would probably make sense to include this in the base JupyterHub implementation, as well. I don't think JupyterHub needs to tolerate spaces in usernames.

**Comment by yuvipanda** [comment]
@minrk I think it shouldn't be in base JupyterHub, since some authenticators do support spaces in user names (Mediawiki I think? Unless that was factored out by someone).

**Comment by mdogy** [comment]
Having the same problem. By mistake using commas and spaces in a list of usernames... it tries to make a single account but fails. The problem is that it becomes very hard to delete that account (get a 500 error even if I change the name not to have spaces). If the OS doesn't support spaces or commas in the names (which is probably a sign of a brain-dead mistake like mine.. rtfm) then it should FAIL to create the user with an error message that says spaces/commas or whatever are not supported on that platform. For reference "uname -a"

Linux jupyter 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

perhaps someone can confirm that if multiple usernames are entered with commas separated by spaces there is no error shown but the account cannot be deleted (500 error) even after the name is changed. Finally did delete after changing name, deleting the directory and rebooting the machine.
